services:
  iptv:
    image: rebeliptv/iptv:latest
    container_name: iptv
    hostname: iptv
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Chicago"
    volumes:
      - iptv-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 8.8.8.8
      - 1.1.1.1
    stop_grace_period: 30s
    restart: unless-stopped

volumes:
  iptv-data:
